-- Run these SQL statements in your Supabase SQL Editor

-- Table for user-provided blog topics
CREATE TABLE IF NOT EXISTS ai_topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  used_at TIMESTAMPTZ
);

-- Table for AI configuration (ON/OFF toggle, API keys, etc.)
CREATE TABLE IF NOT EXISTS ai_config (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster pending topic lookup
CREATE INDEX IF NOT EXISTS idx_ai_topics_status ON ai_topics(status);

-- Add new columns to posts table (if running first time, they'll be created; if not, this adds them)
ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_prompt TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS slug TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS readability_score INTEGER DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS seo_score INTEGER DEFAULT 0;

-- Disable RLS (anon key needs direct access, same as posts table)
ALTER TABLE ai_topics DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_config DISABLE ROW LEVEL SECURITY;
