services:
  - type: web
    name: automme-ai-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY1
        sync: false
      - key: GEMINI_API_KEY2
        sync: false
      - key: TAVILY_API_KEY
        sync: false
